apiVersion: v1
kind: Service
metadata:
  name: {{ include "zero-to-kanban.fullname" . }}-backend
  labels:
    {{- include "zero-to-kanban.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "zero-to-kanban.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 3000
      targetPort: {{ .Values.backend.containerPort }}
