apiVersion: v1
kind: Service
metadata:
  name: {{ include "zero-to-kanban.fullname" . }}-frontend
  labels:
    {{- include "zero-to-kanban.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "zero-to-kanban.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 5173
      targetPort: {{ .Values.frontend.containerPort }}
