apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Zero-To-Kanban-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/julian52575/Zero-To-Kanban.git
    targetRevision: main
    path: deployment/helm/zero-to-kanban
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: Zero-To-Kanban-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
